name: build
on: push
jobs:
  set-matrix:
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: set-env/output variables
      uses: actions-tools/yaml-outputs@v2
      id: yaml
      with:
        file-path: '.github/mci-variables.yaml'
    - id: set-matrix
      run: |
        echo "matrix=$(yq -I=0 -o=json '{"include": .products}' mci-variables.yaml)" >> $GITHUB_OUTPUT
#        echo "matrix=$(yq -I=0 -o=json '.include = .products | del(.products)' mci-variables.yaml)" >> $GITHUB_OUTPUT

  job2:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.set-matrix.outputs.matrix)}}
    steps:
    - run: |
        echo "ARTIFACT_URL: ${{ matrix.ARTIFACT_URL }}"
        echo "PRODUCT_NAME: ${{ matrix.PRODUCT_NAME }}"

