name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: set-env/output variables
      uses: actions-tools/yaml-outputs@v2
      id: yaml
      with:
        file-path: 'mci-variables.yaml'
    - id: set-matrix
      run: |
        echo "${{ steps.yaml.outputs.include }}
        echo 'matrix={"noCoverage":"true","someOtherVar":"false"}' >> $GITHUB_OUTPUT

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "noCoverage: ${{fromJson(needs.job1.outputs.matrix).noCoverage}}"
